import { ASSESSMENT_COMPONENTS } from '@data/components';
import { getPathwayRulesForComponent } from '@data/pathway-rules';

import type { AdoptionStore } from './adoptionState';

const AUTO_LINKED_ACTION_PREFIX = 'pathway-auto-action:';

const PATHWAY_AUTO_OBJECTIVE_PREFIX = 'pathway:auto-objective:';
const LEGACY_VISION_AUTO_OBJECTIVE_PREFIX = 'vision:auto-objective:';

function isAutoGeneratedObjective(objectiveId: string): boolean {
  return (
    objectiveId.startsWith(PATHWAY_AUTO_OBJECTIVE_PREFIX) ||
    objectiveId.startsWith(LEGACY_VISION_AUTO_OBJECTIVE_PREFIX)
  );
}

export function syncPathwayObjectives(store: AdoptionStore): AdoptionStore {
  const pathway = store.orgProfile.cst.pathway;
  const nextObjectives = { ...(store.objectives || {}) };
  const nextDraft = Object.keys(store.currentDraft || {}).reduce<AdoptionStore['currentDraft']>(
    (draft, componentId) => {
      const componentDraft = store.currentDraft[componentId] || {};
      draft[componentId] = Object.keys(componentDraft).reduce<
        AdoptionStore['currentDraft'][string]
      >((entries, lens) => {
        const entry = componentDraft[lens];
        entries[lens] = {
          ...entry,
          actions: (entry.actions || []).filter(
            (action) => !action.id.startsWith(AUTO_LINKED_ACTION_PREFIX)
          ),
        };
        return entries;
      }, {});
      return draft;
    },
    {}
  );

  ASSESSMENT_COMPONENTS.forEach((component) => {
    const pathwayRules = getPathwayRulesForComponent(component.id, pathway);
    if (!pathwayRules) {
      return;
    }

    // Keep only non-auto objectives. Component-specific named outcomes are managed
    // by derived component sync and should remain the canonical set.
    nextObjectives[component.id] = (nextObjectives[component.id] || []).filter(
      (objective) => !isAutoGeneratedObjective(objective.id)
    );
  });

  return {
    ...store,
    currentDraft: nextDraft,
    objectives: nextObjectives,
  };
}
