import { ASSESSMENT_COMPONENTS } from '@data/components';
import { getPathwayRulesForComponent, resolvePathwayCopy } from '@data/pathway-rules';
import type { AdoptionStore, ComponentObjective } from './adoptionState';

const AUTO_LINKED_ACTION_PREFIX = 'pathway-auto-action:';

const PATHWAY_AUTO_OBJECTIVE_PREFIX = 'pathway:auto-objective:';
const LEGACY_VISION_AUTO_OBJECTIVE_PREFIX = 'vision:auto-objective:';

function buildPathwayObjectiveId(pathway: string, componentId: string, index: number): string {
  return `${PATHWAY_AUTO_OBJECTIVE_PREFIX}${pathway}:${componentId}:${index + 1}`;
}

function isAutoGeneratedObjective(objectiveId: string): boolean {
  return objectiveId.startsWith(PATHWAY_AUTO_OBJECTIVE_PREFIX) || objectiveId.startsWith(LEGACY_VISION_AUTO_OBJECTIVE_PREFIX);
}

function createDerivedObjective(
  pathway: string,
  componentId: string,
  objectiveIndex: number,
  objectiveText: string,
  existing?: ComponentObjective
): ComponentObjective {
  return {
    id: buildPathwayObjectiveId(pathway, componentId, objectiveIndex),
    text: objectiveText,
    owner: existing?.owner || '',
    timescale: existing?.timescale || '',
    notes: existing?.notes || '',
    evidence: existing?.evidence || '',
    linkedActions: (existing?.linkedActions || []).filter((link) => !link.actionId.startsWith(AUTO_LINKED_ACTION_PREFIX))
  };
}

function getProgramName(store: AdoptionStore): string {
  const explicitName = (store.orgProfile.projectName || '').trim();
  if (explicitName) {
    return explicitName;
  }

  if (store.orgProfile.cst.type === 'program') {
    return 'program';
  }
  if (store.orgProfile.cst.type === 'initiative') {
    return 'initiative';
  }
  return 'project';
}

export function syncPathwayObjectives(store: AdoptionStore): AdoptionStore {
  const pathway = store.orgProfile.cst.pathway;
  const programName = getProgramName(store);
  const nextObjectives = { ...(store.objectives || {}) };
  const nextDraft = Object.keys(store.currentDraft || {}).reduce<AdoptionStore['currentDraft']>((draft, componentId) => {
    const componentDraft = store.currentDraft[componentId] || {};
    draft[componentId] = Object.keys(componentDraft).reduce<AdoptionStore['currentDraft'][string]>((entries, lens) => {
      const entry = componentDraft[lens];
      entries[lens] = {
        ...entry,
        actions: (entry.actions || []).filter((action) => !action.id.startsWith(AUTO_LINKED_ACTION_PREFIX))
      };
      return entries;
    }, {});
    return draft;
  }, {});

  ASSESSMENT_COMPONENTS.forEach((component) => {
    const pathwayRules = getPathwayRulesForComponent(component.id, pathway);
    if (!pathwayRules) {
      return;
    }

    // Vision uses its own named outcomes system; strip legacy auto-objectives but add no pathway ones
    if (component.id === 'vision') {
      nextObjectives['vision'] = (nextObjectives['vision'] || []).filter(
        (objective) => !isAutoGeneratedObjective(objective.id)
      );
      return;
    }

    const existingObjectives = nextObjectives[component.id] || [];
    const existingById = existingObjectives.reduce<Record<string, ComponentObjective>>((accumulator, objective) => {
      accumulator[objective.id] = objective;
      return accumulator;
    }, {});

    const customObjectives = existingObjectives.filter((objective) => !isAutoGeneratedObjective(objective.id));

    const pathwayObjectives = pathwayRules.checklist.map((rule, index) => {
      const nextId = buildPathwayObjectiveId(pathway, component.id, index);
      return createDerivedObjective(pathway, component.id, index, resolvePathwayCopy(rule.text, programName), existingById[nextId]);
    });

    nextObjectives[component.id] = [...customObjectives, ...pathwayObjectives];
  });

  return {
    ...store,
    currentDraft: nextDraft,
    objectives: nextObjectives
  };
}
