import { ASSESSMENT_COMPONENTS } from '@data/components';
import { getPathwayRulesForComponent, resolvePathwayCopy } from '@data/pathway-rules';
import type { AdoptionStore, ComponentObjective, DraftAction, DraftEntry } from './adoptionState';

const AUTO_LINKED_ACTION_PREFIX = 'pathway-auto-action:';

const PATHWAY_AUTO_OBJECTIVE_PREFIX = 'pathway:auto-objective:';
const LEGACY_VISION_AUTO_OBJECTIVE_PREFIX = 'vision:auto-objective:';

function buildPathwayObjectiveId(pathway: string, componentId: string, index: number): string {
  return `${PATHWAY_AUTO_OBJECTIVE_PREFIX}${pathway}:${componentId}:${index + 1}`;
}

function isAutoGeneratedObjective(objectiveId: string): boolean {
  return objectiveId.startsWith(PATHWAY_AUTO_OBJECTIVE_PREFIX) || objectiveId.startsWith(LEGACY_VISION_AUTO_OBJECTIVE_PREFIX);
}

function createDerivedObjective(
  pathway: string,
  componentId: string,
  objectiveIndex: number,
  objectiveText: string,
  existing?: ComponentObjective
): ComponentObjective {
  return {
    id: buildPathwayObjectiveId(pathway, componentId, objectiveIndex),
    text: objectiveText,
    owner: existing?.owner || '',
    timescale: existing?.timescale || '',
    notes: existing?.notes || '',
    evidence: existing?.evidence || '',
    linkedActions: existing?.linkedActions || []
  };
}

function getProgramName(store: AdoptionStore): string {
  const explicitName = (store.orgProfile.projectName || '').trim();
  if (explicitName) {
    return explicitName;
  }

  if (store.orgProfile.cst.type === 'program') {
    return 'program';
  }
  if (store.orgProfile.cst.type === 'initiative') {
    return 'initiative';
  }
  return 'project';
}

export function syncPathwayObjectives(store: AdoptionStore): AdoptionStore {
  const pathway = store.orgProfile.cst.pathway;
  const programName = getProgramName(store);
  const nextObjectives = { ...(store.objectives || {}) };
  const nextDraft = { ...(store.currentDraft || {}) };

  ASSESSMENT_COMPONENTS.forEach((component) => {
    const pathwayRules = getPathwayRulesForComponent(component.id, pathway);
    if (!pathwayRules) {
      return;
    }

    const existingObjectives = nextObjectives[component.id] || [];
    const existingById = existingObjectives.reduce<Record<string, ComponentObjective>>((accumulator, objective) => {
      accumulator[objective.id] = objective;
      return accumulator;
    }, {});

    const customObjectives = existingObjectives.filter((objective) => !isAutoGeneratedObjective(objective.id));

    // Vision objectives are always auto-linked to at least one action, so nobody lands on an
    // empty "None assigned" objective straight out of the pathway checklist.
    const isVision = component.id === 'vision';
    const primaryLens = component.lenses[0];
    const componentDraft = isVision ? { ...(nextDraft[component.id] || {}) } : null;
    const lensEntry: DraftEntry | null = isVision && primaryLens
      ? componentDraft![primaryLens] || { score: 0, justification: '', evidence: '', actions: [] }
      : null;
    const lensActions: DraftAction[] | null = lensEntry ? [...(lensEntry.actions || [])] : null;

    const pathwayObjectives = pathwayRules.checklist.map((rule, index) => {
      const nextId = buildPathwayObjectiveId(pathway, component.id, index);
      const objective = createDerivedObjective(pathway, component.id, index, resolvePathwayCopy(rule.text, programName), existingById[nextId]);

      if (isVision && primaryLens && lensActions && objective.linkedActions.length === 0) {
        const actionId = `${AUTO_LINKED_ACTION_PREFIX}${pathway}:${component.id}:${index}`;
        if (!lensActions.some((action) => action.id === actionId)) {
          lensActions.push({
            id: actionId,
            text: objective.text,
            owner: '',
            timescale: '',
            status: 'Planned',
            phase: component.phase,
            startDate: '',
            dueDate: '',
            notes: '',
            evidence: '',
            linkedTargets: [{ componentId: component.id, lens: primaryLens }]
          });
        }
        return { ...objective, linkedActions: [{ lens: primaryLens, actionId }] };
      }

      return objective;
    });

    if (isVision && componentDraft && primaryLens && lensEntry && lensActions) {
      componentDraft[primaryLens] = { ...lensEntry, actions: lensActions };
      nextDraft[component.id] = componentDraft;
    }

    nextObjectives[component.id] = [...customObjectives, ...pathwayObjectives];
  });

  return {
    ...store,
    currentDraft: nextDraft,
    objectives: nextObjectives
  };
}
