// One-off refactor: rewires each src/lib/*Automation.ts file to load pathway-2/3 JSON content
// (generated by generatePathwayContent.mjs) alongside pathway-1's, and pick the right one at sync
// time based on store.orgProfile.cst.pathway. Run once with: node scripts/wirePathwayAutomation.mjs

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LIB_DIR = path.join(__dirname, '..', 'src', 'lib');

const IMPORT_RE = /^import (\w+) from '(\.\.\/data\/component-actions\/([\w-]+)-actions\.json)\?raw';$/m;
const SOURCE_RE = /const (\w+_SOURCE) = parseDerivedComponentSource\(\s*([\s\S]*?)\s*\);/;
const FUNC_RE =
  /export function (sync\w+DerivedContent)\(store: AdoptionStore\): AdoptionStore \{\s*return syncDerivedComponentContent\(store, (\w+_CONFIG), (\w+_SOURCE)\);\s*\}/;

function main() {
  const files = readdirSync(LIB_DIR).filter(
    (name) => name.endsWith('Automation.ts') && name !== 'componentDerivedAutomation.ts'
  );

  files.forEach((fileName) => {
    const fullPath = path.join(LIB_DIR, fileName);
    let content = readFileSync(fullPath, 'utf8');

    const importMatch = content.match(IMPORT_RE);
    if (!importMatch) {
      console.warn(`SKIP (no import match): ${fileName}`);
      return;
    }
    const [importLine, varName, jsonPath, stem] = importMatch;

    const sourceMatch = content.match(SOURCE_RE);
    if (!sourceMatch) {
      console.warn(`SKIP (no source match): ${fileName}`);
      return;
    }
    const [sourceBlock, sourceName, sourceArgs] = sourceMatch;
    const configNameMatch = sourceArgs.match(/,\s*(\w+_CONFIG)\s*$/);
    const configName = configNameMatch ? configNameMatch[1] : null;
    if (!configName) {
      console.warn(`SKIP (no config name in source args): ${fileName}`);
      return;
    }

    const funcMatch = content.match(FUNC_RE);
    if (!funcMatch) {
      console.warn(`SKIP (no sync function match): ${fileName}`);
      return;
    }
    const [funcBlock, funcName] = funcMatch;

    const varName2 = `${varName}Pathway2`;
    const varName3 = `${varName}Pathway3`;
    const sourceMapName = sourceName.replace(/_SOURCE$/, '_SOURCE_BY_PATHWAY');

    // 1. Import block: base + pathway2/3 raw imports, plus CstPathwayKey type import.
    const newImports =
      `import ${varName} from '${jsonPath}?raw';\n` +
      `import ${varName2} from '../data/component-actions/${stem}-actions-pathway2.json?raw';\n` +
      `import ${varName3} from '../data/component-actions/${stem}-actions-pathway3.json?raw';\n` +
      `import type { CstPathwayKey } from '@data/cst';`;
    content = content.replace(importLine, newImports);

    // 2. Source: a Record<CstPathwayKey, DerivedComponentSource> instead of a single parsed source.
    const newSource =
      `const ${sourceMapName}: Record<CstPathwayKey, DerivedComponentSource> = {\n` +
      `  'pathway-1': parseDerivedComponentSource(${varName}, ${configName}),\n` +
      `  'pathway-2': parseDerivedComponentSource(${varName2}, ${configName}),\n` +
      `  'pathway-3': parseDerivedComponentSource(${varName3}, ${configName}),\n` +
      `};`;
    content = content.replace(sourceBlock, newSource);

    // 3. Sync function: look up the source by the store's current pathway.
    const newFunc =
      `export function ${funcName}(store: AdoptionStore): AdoptionStore {\n` +
      `  const pathway = store.orgProfile.cst.pathway || 'pathway-1';\n` +
      `  return syncDerivedComponentContent(store, ${configName}, ${sourceMapName}[pathway]);\n` +
      `}`;
    content = content.replace(funcBlock, newFunc);

    // 4. componentDerivedAutomation import needs DerivedComponentSource as a type import now.
    if (!/type DerivedComponentSource/.test(content)) {
      content = content.replace(
        /import \{\n(\s+)clearDerivedComponentContent,\n/,
        `import {\n$1clearDerivedComponentContent,\n$1type DerivedComponentSource,\n`
      );
    }

    writeFileSync(fullPath, content);
    console.log(`Wired ${fileName}`);
  });
}

main();
